help(mean) 
## it shows the function's manual on the help tab

aux <- 2

if(aux < 3) 
  {
   print ("less than 3")
  } else
  {
  print ("not less than 3")
  }
## necessary use "{" to include actions inside case true/false. 
## the "else" has to be on the "}" side, although it fails. Terrible...

vector <- c(1:10)
## create a vector with number between 1 and 10

index <- seq_along (vector)
## create an index with the number of vector's elemements

for(i in index){
## execute 10 times
  print (vector[1:i]+1)
}

sex <- c("M", "H", "H", "H", "M", "M", "H")
## create a vector

list <- as.factor(sex)
## transform a vector into a factor, what means that levels will be created


list
## ex. show the vector and the levels:
-- [1] M H H H M M H
-- Levels: H M

levels(list)
## show only the level

## creating list/ data frames 
# list accept different types of elements.
x <- list(1:5, "Z", TRUE, c("a", "b"))
x
# each argument is one element. A number vector, a char, a boolean, char vector

# data frames work as tables, with x and y axes
my_list <- list(x= 1:3, y=c("a", "b", "c"))

# created 2 vectors

as.data.frame(my_list)
# show the list as a table (frame)

my_list2 <- list(cod = 1:3, name = c("Aron", "Bell", "Chloe"))
# create a table cod X name with 3 lines
as.data.frame (my_list2)



